export default [
    "Toyota",
    "Volkswagen",
    "BMW",
    "Mercedes-Benz",
    "Ford",
    "Nissan",
    "Honda",
    "Porsche",
    "Hyundai Motors",
    "Renault",
    "Peugeot",
    "Chevrolet",
    "Fiat",
    "Audi",
    "Kia Motors",
    "Suzuki",
    "General Motors",
    "Citroën",
    "Daimler",
    "GMC",
    "JLR",
    "Ferrari",
    "Tata Motors",
    "Mazda",
    "Subaru",
    "Lexus",
    "Volvo",
    "MINI",
    "Vauxhall",
    "Isuzu",
    "Dongfeng Motor",
    "Mitsubishi Motors",
    "Mahindra and Mahindra",
    "Daihatsu",
    "Jeep",
    "Kenworth",
    "Dodge",
    "Cadillac",
    "Chrysler",
    "Skoda",
    "Acura",
    "Infiniti",
    "Buick",
    "Lincoln",
    "RAM Trucks",
    "Maruti Suzuki",
    "Smart",
    "Dacia",
    "FAW",
    "Seat"
]